#[shell]
#shell = "/bin/bash"

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
#opacity = 0.85

[window.padding]
x = 5
y = 5

[font]
size = 14

[font.normal]
family = "FiraMono Nerd Font"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
